from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_mujoco.robot_locomotion.mjx.create_env import create_env
from rl_x.environments.custom_mujoco.robot_locomotion.mjx.default_config import get_config
from rl_x.environments.custom_mujoco.robot_locomotion.mjx.general_properties import GeneralProperties


ROBOT_LOCOMOTION_MJX_ENV = extract_environment_name_from_file(__file__)
register_environment(ROBOT_LOCOMOTION_MJX_ENV, get_config, create_env, GeneralProperties)
