from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_maniskill.ant.create_env import create_train_and_eval_env
from rl_x.environments.custom_maniskill.ant.default_config import get_config
from rl_x.environments.custom_maniskill.ant.general_properties import GeneralProperties


CUSTOM_MANISKILL_ANT = extract_environment_name_from_file(__file__)
register_environment(CUSTOM_MANISKILL_ANT, get_config, create_train_and_eval_env, GeneralProperties)