from ml_collections import config_dict


def get_config(environment_name):
    config = {
        "name": environment_name,
        "nr_envs": 1,
        "seed": 1,
        "device": "cpu",
        "render": False,
        "render_callback_type": "debug_callback",
        "copy_train_env_for_eval": False,
        "train_robot": "unitree_g1",
        "dataset": "lafan",
        "motion_files": "",
        "motion_fps": 30.0,
        "native_joint_order": False,
        "quaternion_order": "wxyz",
        "control_decimation": 4,
        "episode_length_seconds": 10.0,
        "control": {
            "module": "pd",
            "pd": {
                "action_scale": 0.25,
            },
        },
        "action_clip": 100.0,
        "observation": {
            "joint_position_range": 3.14,
            "joint_velocity_range": 100.0,
            "action_range": 10.0,
            "linear_velocity_range": 10.0,
            "angular_velocity_range": 50.0,
            "relative_position_range": 1.0,
            "clip": 10.0,
        },
        "random_start": True,
        "adaptive_sampling": True,
        "adaptive_uniform_ratio": 0.1,
        "anchor_body": "torso_link",
        "tracked_bodies": [
            "trunk",
            "left_hip_roll_link",
            "left_knee_link",
            "left_ankle_roll_link",
            "right_hip_roll_link",
            "right_knee_link",
            "right_ankle_roll_link",
            "torso_link",
            "left_shoulder_roll_link",
            "left_elbow_link",
            "left_wrist_yaw_link",
            "right_shoulder_roll_link",
            "right_elbow_link",
            "right_wrist_yaw_link",
        ],
        "object": {
            "type": "box",
            "pos": [1.0, 0.0, 1.0],
            "quat": [1.0, 0.0, 0.0, 0.0],
            "rgba": [0.65, 0.35, 0.15, 1.0],
            "solref": [0.02, 1.0],
            "contype": 2,
            "conaffinity": 3,
            "half_size": [0.2, 0.2, 0.2],
            "center": [0.0, 0.0, 0.0],
            "mass": 2.0,
            "mesh_path": "",
            "friction": [1.0, 0.005, 0.0001],
        },
        "reward": {
            "module": "default",
            "default": {
                "anchor_position_coeff": 0.5,
                "anchor_position_sigma": 0.3,
                "anchor_orientation_coeff": 0.5,
                "anchor_orientation_sigma": 0.4,
                "body_position_coeff": 1.0,
                "body_position_sigma": 0.3,
                "body_orientation_coeff": 1.0,
                "body_orientation_sigma": 0.4,
                "body_linear_velocity_coeff": 1.0,
                "body_linear_velocity_sigma": 1.0,
                "body_angular_velocity_coeff": 1.0,
                "body_angular_velocity_sigma": 3.14,
                "object_position_coeff": 1.0,
                "object_position_sigma": 0.3,
                "object_orientation_coeff": 1.0,
                "object_orientation_sigma": 0.4,
                "action_rate_coeff": -0.1,
                "joint_limits_coeff": -10.0,
                "soft_joint_position_limit": 0.9,
                "undesired_contacts_coeff": -0.1,
                "contact_force_threshold": 1.0,
                "contact_history_length": 3,
                "allowed_contact_names": [
                    "left_ankle_roll_link", "right_ankle_roll_link",
                    "left_wrist_yaw_link", "right_wrist_yaw_link",
                    "left_foot_contact_point", "right_foot_contact_point",
                ],
            },
        },
        "termination": {
            "module": "tracking_error",
            "tracking_error": {
                "anchor_height_threshold": 0.5,
                "anchor_orientation_threshold": 0.8,
                "body_height_threshold": 0.25,
                "object_position_threshold": 0.25,
                "object_orientation_threshold": 0.8,
                "tracked_body_names": [
                    "left_ankle_roll_link",
                    "right_ankle_roll_link",
                    "left_wrist_yaw_link",
                    "right_wrist_yaw_link",
                ],
            },
        },
        "adaptive_alpha": 0.001,
        "domain_randomization": {
            "initial_state": {
                "module": "default",
                "default": {
                    "enable_randomization": True,
                    "joint_position": 0.1,
                    "soft_joint_position_limit": 0.95,
                    "root_position": [0.05, 0.05, 0.01],
                    "root_orientation": [0.1, 0.1, 0.2],
                    "root_linear_velocity": [0.5, 0.5, 0.2],
                    "root_angular_velocity": [0.52, 0.52, 0.78],
                    "object_position": [0.05, 0.05, 0.0],
                },
            },
            "mujoco_model": {
                "module": "default",
                "sampling": {"module": "on_creation"},
                "default": {
                    "enable_randomization": True,
                    "robot_sliding_friction_range": [0.3, 1.2],
                    "material_buckets": 64,
                    "torso_com_range": [0.025, 0.05, 0.05],
                    "object_sliding_friction_range": [0.1, 0.6],
                    "object_mass_add_range": [1.0, 4.0],
                    "object_inertia_x_scale_range": [0.5, 1.5],
                },
            },
            "actuator": {
                "module": "default",
                "bias_sampling": {"module": "on_creation"},
                "gain_sampling": {"module": "on_reset"},
                "default": {
                    "enable_randomization": True,
                    "enable_joint_bias": True,
                    "joint_bias_range": [-0.01, 0.01],
                    "enable_gain_randomization": False,
                    "proportional_gain_range": [0.9, 1.1],
                    "derivative_gain_range": [0.9, 1.1],
                },
            },
            "action_delay": {
                "module": "default",
                "sampling": {"module": "on_reset"},
                "default": {
                    "enable_randomization": False,
                    "delay_steps_range": [0, 1],
                },
            },
            "perturbation": {
                "module": "default",
                "sampling": {
                    "module": "step_probability",
                    "step_probability": {"probability": 0.002},
                },
                "default": {
                    "enable_randomization": True,
                    "root_velocity": [0.5, 0.5, 0.2, 0.52, 0.52, 0.78],
                },
            },
            "observation_noise": {
                "module": "default",
                "default": {
                    "enable_randomization": True,
                    "reference_anchor_orientation": 0.05,
                    "base_angular_velocity": 0.2,
                    "joint_position": 0.01,
                    "joint_velocity": 0.5,
                },
            },
        },
    }

    return config_dict.ConfigDict(config)
