from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_interface.prototype.create_env import create_env
from rl_x.environments.custom_interface.prototype.default_config import get_config
from rl_x.environments.custom_interface.prototype.general_properties import GeneralProperties


CUSTOM_ENVIRONMENT_PROTOTYPE = extract_environment_name_from_file(__file__)
register_environment(CUSTOM_ENVIRONMENT_PROTOTYPE, get_config, create_env, GeneralProperties)
