from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from rl_x.algorithms.ppo_memory_actions.flax.ppo_memory_actions import PPO_Memory_Actions
from rl_x.algorithms.ppo_memory_actions.flax.default_config import get_config
from rl_x.algorithms.ppo_memory_actions.flax.general_properties import GeneralProperties


PPO_MEMORY_ACTIONS_FLAX = extract_algorithm_name_from_file(__file__)
register_algorithm(PPO_MEMORY_ACTIONS_FLAX, get_config, PPO_Memory_Actions, GeneralProperties)
