from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from rl_x.algorithms.ppo_memory_actions.pytorch.ppo_memory_actions import PPO_Memory_Actions
from rl_x.algorithms.ppo_memory_actions.pytorch.default_config import get_config
from rl_x.algorithms.ppo_memory_actions.pytorch.general_properties import GeneralProperties


PPO_MEMORY_ACTIONS_PYTORCH = extract_algorithm_name_from_file(__file__)
register_algorithm(PPO_MEMORY_ACTIONS_PYTORCH, get_config, PPO_Memory_Actions, GeneralProperties)
