from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from rl_x.algorithms.ppo_transformer.pytorch.ppo_transformer import PPO_Transformer
from rl_x.algorithms.ppo_transformer.pytorch.default_config import get_config
from rl_x.algorithms.ppo_transformer.pytorch.general_properties import GeneralProperties


PPO_TRANSFORMER_PYTORCH = extract_algorithm_name_from_file(__file__)
register_algorithm(PPO_TRANSFORMER_PYTORCH, get_config, PPO_Transformer, GeneralProperties)
