from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_mujoco.ant.mujoco.create_env import create_train_and_eval_env
from rl_x.environments.custom_mujoco.ant.mujoco.default_config import get_config
from rl_x.environments.custom_mujoco.ant.mujoco.general_properties import GeneralProperties


CUSTOM_MUJOCO_ANT = extract_environment_name_from_file(__file__)
register_environment(CUSTOM_MUJOCO_ANT, get_config, create_train_and_eval_env, GeneralProperties)
