from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from rl_x.algorithms.ppo_transformer.flax_full_jit.ppo_transformer import PPO_Transformer
from rl_x.algorithms.ppo_transformer.flax_full_jit.default_config import get_config
from rl_x.algorithms.ppo_transformer.flax_full_jit.general_properties import GeneralProperties


PPO_TRANSFORMER_FLAX_FULL_JIT = extract_algorithm_name_from_file(__file__)
register_algorithm(PPO_TRANSFORMER_FLAX_FULL_JIT, get_config, PPO_Transformer, GeneralProperties)
