from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from rl_x.environments.custom_mujoco.robot_locomotion.mjx_warp.create_env import create_train_and_eval_env
from rl_x.environments.custom_mujoco.robot_locomotion.mjx_warp.default_config import get_config
from rl_x.environments.custom_mujoco.robot_locomotion.mjx_warp.general_properties import GeneralProperties


ROBOT_LOCOMOTION_MJX_WARP_ENV = extract_environment_name_from_file(__file__)
register_environment(ROBOT_LOCOMOTION_MJX_WARP_ENV, get_config, create_train_and_eval_env, GeneralProperties)
