from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from rl_x.algorithms.ppo_history_window.pytorch.ppo_history_window import PPO_History_Window
from rl_x.algorithms.ppo_history_window.pytorch.default_config import get_config
from rl_x.algorithms.ppo_history_window.pytorch.general_properties import GeneralProperties


PPO_HISTORY_WINDOW_PYTORCH = extract_algorithm_name_from_file(__file__)
register_algorithm(PPO_HISTORY_WINDOW_PYTORCH, get_config, PPO_History_Window, GeneralProperties)
